spring.application.name=menu

#Config para la base de datos:

spring.datasource.url=jdbc:mysql://localhost:3306/db_menu?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Config de JPA / HIBERNATE

#El hibernate creara o actualizara cada tabla automaticamente a medida que vaya haciendo codigo
spring.jpa.hibernate.ddl-auto=update

# El dialecto específico para MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Servidor web (para que no choque después con los otros microservicios)
server.port=8081